version: '3'
services:
  write_service:
    build: ./clojure-leiningen-rest-service
    ports:
      - "3000:3000"
  stream_processor:
    build: ./java-dropwizard-rest-service
    ports:
      - "5005:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
  read_service:
    build: ./java-dropwizard-rest-service
    ports:
      - "8080:8080"
      - "5006:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
      - makefile_microservices
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    volumes:
      - zookeeper:/opt/zookeeper-3.4.6/data
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    volumes:
      - kafka:/kafka
    networks:
      - default
      - makefile_microservices
networks:
  makefile_microservices:
    external: true
volumes:
  postgres:
  zookeeper:
  kafka:
